language: node_js
node_js:
  - "5.6.0"
services:
  - mongodb
  - redis
env:
    - TEST_DIR=GameServer
script: cd $TEST_DIR && npm install && mocha test

before_deploy:
  - cd ..
  - sh before_deploy.sh

deploy:
  - provider: heroku
    api_key: b0b132e4-1f7d-4bd4-a5b0-cd74599d12b4
    app: frima-server-test
    on:
      branch: server_release

  - provider: heroku
    api_key: b0b132e4-1f7d-4bd4-a5b0-cd74599d12b4
    app: frima-cms-server
    on:
      branch: cms_server_release
