language: node_js
node_js:
  - "5.6.0"

notifications:
  slack: glo-3002-frima:ZJ8XIia7RmUgdioopRwOxWU5
  

deploy:
  - provider: heroku
    api_key: b0b132e4-1f7d-4bd4-a5b0-cd74599d12b4 #TODO: Secure key
    app:
      CMS: frima-client-1
    on:
      branch: client_release