language: node_js
node_js:
  - "5.6.0"
services:
  - mongodb
  - redis
env:
  global:
    - secure: GPNpxvVLYPLHdIW9eSM3gJbEqwGYSzQo7txWygTICfJAdoP2cOnL+qHIJxUqu0CBl3a8oZNjLCgZLbXteYnXytxRrRHWk9USQqeTAHb18P4OMB8douhKIFzJQz4UMoLiTWzwVd+uj3QI3TSPourMVqfai8WeIVnptUw2KPvtPEfP35G5UvSepYr3NTs1k86JKXtCkgLe8UiW4SK00tXPkHZmdrLPUsk6n9WMD5NJHSQTi2fMlX6O4YVgBxIoXwVXfTcdqs1r0vDFKpLzZMUoAjQhnGuzU8ryWCfusmLGQzAFg7vXqnVdnardKp+G0EqD66hALEqsCRtQCfqyUZCLt5L0JYXiD0TlkFZecj2ptOV+C7I5YbC//bOCCAQDfdzKT/JSvgZH8f6M7y5qRkGvn79HE0o2KyynUwrt2hfu6/N+7w7UuVDKq7v/BqHX6Nt4AKdu9E2Pm5HxvhhLvcZCnotgv2BOJKOEN7B2Z0COTyPpp+RmBJTdCvTpO4uvqEze9ALJwDkfmaFd4RiUnFmVLkhd3GnbKjUfEmsyEJj+fq+h6dwzobuspFH26vXeOCXKnWctQNEhZnmf5uqzjksFWfQ6O0jZlOjq2RV6apWSbXkomCApQ2snBDCjw3UI4FMBbrP7gRbcxppT/vp3UZVZJuwOfGPOUnK98VFW2ZJPKvA=
    - TEST_DIR=GameServer
script: cd $TEST_DIR && npm install && mocha test

after_success:
  - gem install heroku
  # Add your Heroku git repo:
  - git remote add heroku git@heroku.com:frima-server-test.git
    # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
    # Clear your current Heroku SSH keys:
  - heroku keys:clear
    # Add a new SSH key to Heroku
  - yes | heroku keys:add
    # Push to Heroku!
  - yes | git subtree push --prefix GameServer heroku master || exit 1
